### PR TITLE
Iteration 3 sleep

### LINKED ISSUE #8: Iteration 3 - Sleep
**Describe the bug/issue**
- CommunitySleep class is not passing all tests

**To Reproduce (if bug)**
1. run ```npm test tests/CommunitySleep-test.js```
2. see errors: 
```
 TypeError: Cannot read property 'to' of undefined
 TypeError: communitySleep.calculateSleepQualityWeek is not a function
 TypeError: communitySleep.calculateAvgSleepQuality is not a function
 TypeError: communitySleep.findBestQualitySleepers is not a function
 TypeError: communitySleep.findMostHrsSleepers is not a function
```

**Expected behavior**
- The first error should actually run the test for calculateSleepWeek, though it will come back as an unexpected return since calculateSleepWeek is declared but returns no values.
- The other functions are not yet declared so will continue to show that TypeError.

**Additional context**
- The first error can be fixed by changing the parentheses around the function calls. 
```
 expect(communitySleep.calculateSleepWeek(40, "2019/08/10", "2019/08/16").to.deep.equal([4.1, 4.8, 3.4, 9.2, 6.0, 6.8, 9.3]));
```
The way it's written, the expect() needs to only contain the cs.csw(#) like " expect( cs.csw(#) ) " 
so it should be:
```
 expect(communitySleep.calculateSleepWeek(40, "2019/08/10", "2019/08/16")).to.deep.equal([4.1, 4.8, 3.4, 9.2, 6.0, 6.8, 9.3]);
```

- The functions that haven't been written yet remind me closely of ones from iteration 4 and I highly recommend reviewing parallels. 
    - for the functions to grab stuff for the week, CommunityActivity has this which might help:
```
 findWeekActivities(startDate, endDate, user) {
    const startNum = this.dateToNumber(startDate)
    const endNum = this.dateToNumber(endDate)
    const userActivities = this.findAllUserActivities(user)
    return userActivities.filter(activity => {
      const activityDateNum = this.dateToNumber(activity.date)
      return activityDateNum >= startNum && activityDateNum <= endNum
    })
  }
```

 -  Once we get a week's worth of the sleep data as an array of [sleep, sleep, sleep], we can probably get a total hours slept (via reduce) and array of just the sleep qualities each day (via map) fairly easily
    - The average for all users sleep quality is close to the CommunityAverage method:

```
 findCommunityAverage(date, fitnessType) {
    const allActivitesForDate = this.activities.filter(activity => activity.date === date)
    const totalActivity = allActivitesForDate.reduce((activityTotal, activity) => activityTotal + activity[fitnessType], 0)

    return Math.round(totalActivity / allActivitesForDate.length)
  }
```

- For the users who average sleep quality > 3 for a week, that's a tricky one to get, but if you're interested in my pseudocode thought, I might break it down like:
  - the function takes in a startDate, endDate, and arrayOfUsers
  - calls a function similar to findWeekActivites()  for each user's userID in the arrayOfUsers (we can call it using our userRepository), return an array of all users sleep within that week
   - again using the array of users for each userID, we reduce to get each user's average sleep within that weekofCommunitySleep array,  and return both the average and the userID
   - we filter that array of averagesAndIDs for ones over 3, and get a returned array of just those users who average that good sleep quality (not me, clearly)
    - we use all those ids to grab those users (their names, or whatever) from the userRepository using the method in that class  ```UserRepository.getUserData(id)```

- For the given day users that slept the most, CommunityActivity has this which might help:
```
findRecordStairs(user) {
    const userActivities = this.findAllUserActivities(user)
    const allStairsClimbed = userActivities.map(activity => activity.stairsClimbed)
    return Math.max(...allStairsClimbed)
  }
```

- it looks like the two methods that get averages you have written for average sleep hours for a day and quality for a day are basically the same function. What if they intook a 'sleepAttribute' parameter and we could call sleeper[sleepAttribute] to return either the hours or quality?

- Overall the stuff you have looks solid! Thanks for getting those up!

- I'm going to do a little bit of rearranging of the html, css, and scripts mainly to just display the charts for each of these, and I'm making some helper functions to be able to parse the return values of the sleep hours and quality over the course of the week into those charts easily -- getData() and chartIt()
- I might also mess with the extensions. I'm doing a few mid-mod assessment prep things tomorrow so I'll see what I get done!

### PR DESCRIPTION
**Pull request by conconartist**
**Changes:**

- Add test blocks for Sleep and CommunitySleep classes
- Add functionality and methods for Sleep and Community Sleep classes to complete iteration 3
- Update scripts.js for display functionality
- Refactor CommunityHydration class and corresponding tests for bug fix
- Refactored methods to find averages in CommunitySleep class to access objects for display 

**Issues:**
- Will need to work on formatting for next iteration to hide graph and show graph elements

- [ ] DRY and SRP
- [ ] Tested Locally

**How to Review Changes or Manually Test Code:**
- View classes and tests in Sleep.js, Sleep-test.js, CommunitySleep.js, and CommunitySleep-test.js 
- View scripts.js and index.html to view display functionality
- Open index.html in browser to view displays for each dashboard category

**Notes:**
- I refactored the methods to find weekly totals to return object data as requested for graph display

### CODE REVIEW

File: src/scripts.js [hunk 1]
```diff
@@ -184,6 +191,11 @@ const showStairsStatsWeek = (startDate, endDate) => {
     `<article class="stairs-stats-week">Stairs Climbed over the week of ${startDate}-${endDate}:` + activitiesDisplay + '</article>')
 }
 
+const showSleepStats = () => {
+  showLatestSleepStatsUser();
+  showAllSleepQuantity();
+  showAllSleepQuality();
+}
```
Comment (srslie) [inline src/scripts.js:212]: Love chunking all these for readability!

File: src/CommunitySleep.js [hunk 2]
```diff
@@ -41,36 +41,24 @@ class CommunitySleep {
...
     const sleepWeekTotals = [];
     const startDateNumber = this.convertDateString(startDate);
     const endDateNumber = this.convertDateString(endDate);
     const userSleep = this.findUserSleepData(userID);
     const sleepDates = userSleep.filter(sleeper => {
       const sleepDateToNumber = this.convertDateString(sleeper.date)
       if(sleepDateToNumber >= startDateNumber && sleepDateToNumber <= endDateNumber){
-        sleepWeekTotals.push(sleeper.hoursSlept);
+        sleepWeekTotals.push(sleeper);
       }
```
Comment (srslie) [inline src/CommunitySleep.js:53]: Thank you! That makes display in chart easier!

File: src/CommunitySleep.js [hunk 3]
```diff
@@ -41,36 +41,24 @@ class CommunitySleep {
...
-      if(sleepDateToNumber >= startDateNumber && sleepDateToNumber <= endDateNumber){
-        sleepWeekTotals.push(sleeper.sleepQuality);
-      }
-    })
-    return sleepWeekTotals;
-  }
   calculateAvgSleepQualityWk(userID, startDate, endDate) {
-    const sleepWeek = this.calculateSleepQualityWeek(userID, startDate, endDate);
-    const sleepWeekAvg = (sleepWeek.reduce((a, b) => a + b, 0))/7
+    const something = this.calculateSleepStatsWeek(userID, startDate, endDate);
```
Comment (srslie) [inline src/CommunitySleep.js]: Haha, I actually think what you had, "sleepWeek" would be a nice name for that "something" variable. Nice work here!

File: src/CommunitySleep.js [hunk 4]
```diff
@@ -68,11 +68,35 @@ class CommunitySleep {
...
+     const avgSleepQuality = (sleepQualityAllUsers.reduce((a, b) => a + b, 0)) / sleepQualityAllUsers.length;
+     return Math.round(avgSleepQuality * 10) / 10;
+  }
+
+  findBestQualitySleepers(startDate, endDate) {
+    const bestSleepers = []
+    const startDateNumber = this.convertDateString(startDate);
+    const endDateNumber = this.convertDateString(endDate);
+    const sleepWeek = this.sleeps.filter(sleeper => {
+      const sleepDateToNumber = this.convertDateString(sleeper.date)
```
Comment (srslie) [inline src/CommunitySleep.js]: I like the name sleepDateToNumber, but the 'To' almost makes it seem like it would be a function name because it implies action, maybe just sleepDateNumber or sleepDateAsNumber? The value getting stored in that variable is a number.  Minor thing

File: src/CommunitySleep.js [hunk 5]
```diff
@@ -68,11 +68,35 @@ class CommunitySleep {
...
+      if (sleepDateToNumber >= startDateNumber && sleepDateToNumber <= endDateNumber) {
+        return sleeper;
```
Comment (srslie) [inline src/CommunitySleep.js]: You don't need this return sleeper code block--I think if you just return the conditional so ```return (sleepDateToNumber >= start... )``` it will return the elements of the array (sleepers in this case) that pass that condition. 

The goal of the filter callback function is to return a conditional that will evaluate to a boolean, and the method itself will implement a return of the array that it pushes all the elements which pass that condition into.

File: src/CommunityHydration.js [hunk 6]
```diff
@@ -20,7 +20,7 @@ class CommunityHydration {
     const userWater = this.hydrations.filter(water => (water.userID === userID));
     const waterConsumed = userWater.map(water => water.numOunces);
     const avgWaterConsumed = (waterConsumed.reduce((a, b) => a + b, 0)) / waterConsumed.length;
-    return avgWaterConsumed;//refactor to truncate long decimals
+    return Math.round(avgWaterConsumed * 10) / 10
```
Comment (srslie) [inline src/CommunityHydration.js:23]: Sleek.

File: src/CommunitySleep.js [hunk 7]
```diff
@@ -0,0 +1,102 @@
...
+    const sleepHours = [];
+    this.sleeps.forEach(sleeper => {
+      sleepHours.push(this.findHrsSleptOnDay(sleeper.userID, date))
+      const longestSleep = Math.max(...sleepHours);
+      if(longestSleep === sleeper.hoursSlept && date === sleeper.date) {
+        sleepers.push(sleeper.userID);
+      }
+    })
+    return sleepers;
+  }
```
Comment (srslie) [inline src/CommunitySleep.js:98]: This code is a bit confusing for me. I think some of it is naming ('sleep' losing its meaning to you at all?) but I'm also not sure I entirely follow.  Maybe we can refactor it? I might have some issues with my max function too, now I'm looking at this.

First, the longestSleep declaration inside of the forEach loop is sorta weird, because for every element of the this.sleeps array, it creates a new longestSleep variable grabbing a max of the hours just pushed into sleepHours.

Since longestSleep gets set to the new maximum sleep hours of all the users as it goes, it may end up pushing extra stuff into the sleepers array just because they happen to be on that date and the highest hoursSlept so far (as you go through each element). I think this code would be vulnerable to bugs.

I might instead break it down to into the sleeps that happened on that date, and then go in and reduce (so manually do the calculation in case two have the same high number of sleeps) to return an array of the longest sleepers. Something like: 
```
findMostHoursSleepers(date) {
   const sleepsOnDate = this.sleeps.filter(sleep => sleep.date === date)
   const sleepers = sleepsOnDate.reduce((longestSleepers, sleeper, index)  => {
      if (sleeper.hoursSlept > longestSleepers[0].hours) {
        longestSleepers = [ {sleeperIndex: index, hours: sleeper.hoursSlept} ]
      } else if (sleeper.hoursSlept === longestSleepers[0].hours) {
        longestSleepers.push( {sleeperIndex: index, hours: sleeper.hoursSlept} )
      }
    return longestSleepers
   }, [ {sleeperIndex: 0, hours: 0} ])
  return sleepers.map(sleeperReference => sleepsOnDate[sleeperReference.sleeperIndex])
}

Comment (srslie) [reply src/CommunitySleep.js:98]: ^ The above code block is a bit dense so if you want to hop on a call let me know!

File: src/CommunitySleep.js [hunk 8]
```diff
@@ -0,0 +1,102 @@
...
+    const sleepQualityAllUsers = this.sleeps.map(allSleepers => allSleepers.sleepQuality);
+     const avgSleepQuality = (sleepQualityAllUsers.reduce((a, b) => a + b, 0)) / sleepQualityAllUsers.length;
+     return Math.round(avgSleepQuality * 10) / 10;
+  }
+
+  findBestQualitySleepers(startDate, endDate) {
+    const bestSleepers = []
+    const startDateNumber = this.convertDateString(startDate);
+    const endDateNumber = this.convertDateString(endDate);
+    const sleepWeek = this.sleeps.filter(sleeper => {
```
Comment (srslie) [inline src/CommunitySleep.js:75]: I think this returns a 'sleep' object, not the specific sleeper, so maybe that name in the callback function can change? It's hard to keep all these similar sleep-related names apart so the more specific the better.

File: src/CommunitySleep.js (hunk 2 above)
Comment (srslie) [reply src/CommunitySleep.js:53]: Also I'm noticing that apart from userSleep, this grabbing of a specific week is similar to what you do below in findBestQualitySleepers to get a week's worth of user data. Maybe factoring out just the date conversion and grabbing that week worth of sleep data can be one function, adding the userID filter for these ones (nice using it below for the averages) can be another helper function. This is more just thoughts for a future refactor.

File: src/CommunitySleep.js (hunk 5 above)
Comment (srslie) [reply src/CommunitySleep.js]:
```
 const sleepsWeek =  this.sleeps.filter(sleep => {
      const sleepDateNum = this.convertDateString(sleeper.date)
      return sleepDateNum >= startNum && activityDateNum <= endNum
    })
 ```

File: src/CommunitySleep.js [hunk 9]
```diff
@@ -0,0 +1,102 @@
...
+      if (sleepDateToNumber >= startDateNumber && sleepDateToNumber <= endDateNumber) {
+        return sleeper;
+      }
+    })
+    const filterSleepers = sleepWeek.filter(sleeper => {
+      const avgSleepQual = this.calculateAvgSleepQualityWk(sleeper.userID, startDate, endDate)
+      if(!bestSleepers.includes(sleeper.userID) && avgSleepQual > 3){
+        bestSleepers.push(sleeper.userID)
+      }
+    })
```
Comment (srslie) [inline src/CommunitySleep.js:84]: This looks more like a forEach than a filter, because you're pushing things into an array. So the filter will do that for you, essentially that "bestSleepers" array would be made by the filter method if it passed your ```!bestSleepers.includes(sleeper.userID) && avgSleepQual > 3``` condition.  So I would either change this into a just the return of that condition or a forEach.

File: src/CommunitySleep.js [hunk 10]
```diff
@@ -0,0 +1,102 @@
...
+    return userSleep;
+  }
+
+  calculateAvgSleepHrsPerDay(userID) {
+    const userSleep = this.sleeps.filter(sleeper => (sleeper.userID === userID));
+    const amountSlept = userSleep.map(sleeper => sleeper.hoursSlept);
+    const avgHoursSlept = (amountSlept.reduce((a, b) => a + b, 0)) / amountSlept.length;
+    return Math.round(avgHoursSlept * 10) / 10;
+  }
+
```
Comment (srslie) [inline src/CommunitySleep.js:26]: These two Avg functions are pretty much the same. I have some of them too. Let's leave them for now but I think we can do a ```calculateAverageOf(someProperty)``` in the User class or something that will clean up this wetness.

File: src/CommunityHydration.js [hunk 11]
```diff
@@ -1,44 +1,44 @@
...
-          weekWaterTotals.push(water.numOunces);
-        }
-       })
+    const userWater = this.findUserWaterData(userID);
+
+    const waterDates = userWater.filter(water => {
+      const waterDateToNumber = this.convertDateString(water.date)
+      if(waterDateToNumber >= startDateNumber && waterDateToNumber <= endDateNumber) {
+        weekWaterTotals.push(water);
+      }
```
Comment (srslie) [inline src/CommunityHydration.js:41]: This filter looks like a forEach. See comments below on the filters to refactor this into a filter!

File: tests/CommunitySleep-test.js [hunk 12]
```diff
@@ -0,0 +1,108 @@
...
+      {"userID": 39, "date": "2019/08/18", "hoursSlept": 6.8, "sleepQuality": 3.8},//9
+      {"userID": 40, "date": "2019/08/18", "hoursSlept": 6.9, "sleepQuality": 3.3},
+      {"userID": 41, "date": "2019/08/18", "hoursSlept": 9.2, "sleepQuality": 2.6},
+      {"userID": 39, "date": "2019/08/19", "hoursSlept": 8.4, "sleepQuality": 4.2},//10
+      {"userID": 40, "date": "2019/08/19", "hoursSlept": 6.5, "sleepQuality": 3.8},
+      {"userID": 41, "date": "2019/08/19", "hoursSlept": 4.0, "sleepQuality": 3.8},
+      {"userID": 39, "date": "2019/08/20", "hoursSlept": 4.2, "sleepQuality": 1.4},//11
+      {"userID": 40, "date": "2019/08/20", "hoursSlept": 6.8, "sleepQuality": 1.1},
+      {"userID": 41, "date": "2019/08/20", "hoursSlept": 6.8, "sleepQuality": 3.8},
+    ]);
```
Comment (srslie) [inline tests/CommunitySleep-test.js:45]: Nice big sample set :)

**Review by srslie — CHANGES_REQUESTED** [review]
Hey nice job!

I saw some potential issues that we may want to refactor. 

Overall it seems like you're overcomplicating filters and basically using them as forEachs. I think filters are really great for this project so maybe you can take a look at the comments and refactor those. 

Biggest bug was in the findMostHoursSleepers method, I think that one might give us some incorrect users back as it's currently written. I did add something I think would work instead, and it made me rethink how I'm doing my finding the record/using Math.max so I appreciated seeing that code.

Let me know if you have any questions on the comments!

File: src/CommunitySleep.js (hunk 3 above)
Comment (conconartist) [reply src/CommunitySleep.js]: @srslie Oh whoops-- that was a placeholder that I forgot to change.

File: src/CommunitySleep.js (hunk 2 above)
Comment (conconartist) [reply src/CommunitySleep.js:53]: That's something that I'd like to accomplish but refactoring the methods to return objects took a lot longer than I expected.  If I have time, that's something I'll prioritize in the future.

File: src/CommunitySleep.js (hunk 3 above)
Comment (conconartist) [reply src/CommunitySleep.js]: @srslie just fixed

File: src/CommunitySleep.js (hunk 4 above)
Comment (conconartist) [reply src/CommunitySleep.js]: @srslie updated!

File: src/CommunitySleep.js (hunk 5 above)
Comment (conconartist) [reply src/CommunitySleep.js]: @srslie fixed

File: src/CommunitySleep.js (hunk 7 above)
Comment (conconartist) [reply src/CommunitySleep.js:98]: @srslie  I'm not sure I follow what you mean.  As far as what I thought I accomplished, I used the method to find how many hours for each user were spent sleeping on a certain date and pushed to an array, and then the new array is assessed through the conditional to meet the requirements of matching the date and hours slept.  You would have to show me where and how you're thinking it could be buggy, since it passed my tests.  Also, the function (according to the spec) is allowed to return more than one user, or are you implying they'd have different values for sleep hours?

File: src/CommunitySleep.js (hunk 8 above)
Comment (conconartist) [reply src/CommunitySleep.js:75]: @srslie I mainly used 'sleeper' as a general placeholder for 'sleep' to separate it in my head from the action of 'sleep'.  Sleeper to me is the object, but i can change it if it's confusing to you.

File: src/CommunitySleep.js (hunk 9 above)
Comment (conconartist) [reply src/CommunitySleep.js:84]: @srslie then why did it work???? I'm not sure what you mean by "I would either change this into a just the return of that condition".

File: src/CommunitySleep.js (hunk 10 above)
Comment (conconartist) [reply src/CommunitySleep.js:26]: @srslie yes, I mentioned that aspect but wanted to focus on getting the thing to work.

File: src/CommunitySleep.js (hunk 8 above)
Comment (srslie) [reply src/CommunitySleep.js:75]: No worries, it's a minor thing and as long as it makes sense and the function works, we can worry about names later. Sleeper to me implies a user, but I can see how it's the object to you.

File: src/CommunitySleep.js (hunk 9 above)
Comment (srslie) [reply src/CommunitySleep.js:84]: It works because it's an iterator method, and all these methods basically work by being 'for loops' that go through the array and have some special properties. Filters are set up sorta like:
```
let elementsThatPassFilterCondition = [ ]
for (var i = 0; i < array.length; i++) {
    if (array[i] === condition) {
       elementsThatPassFilterCondition.push(array[i]
    }
}
```
So, you're just coding in some code that's already in there because of the filter. Totally fine to refactor later, but just a note for using that method.

**Comment by srslie** [comment]
Thanks for making those changes!
