### PR TITLE
Iteration 2

### LINKED ISSUE #5: Connecting Hydration Stats
**Describe the bug/issue**

For the Hydration and CommunityHydration classes, I believe the methods and constructor are set up correctly to access the data from hydration.js.  However, connecting to the data via scripts.js is not resulting in the outcome I'm hoping for, so I'm assuming that there's something missing in how it's currently trying to access the data to display.  

**To Reproduce (if bug)**
1. Go to scripts.js, open in text editor
3. Scroll down to showHydrationStats and showHydrationStatsWeek to view functions.  (Scroll up to top for instantiations of classes).  
4. See error: Right now, I have the interpolations as placeholders since they are not accurately accessing the methods at this point.  

**Expected behavior**
When opening the index in the browser, you should see stats on window load under the category for water that show the water consumed for the day.  Under the graph section, you should see on load the weekly statistics for water consumption for the user on each day of a given week.  

**As a** user, **When I visit** the home view page for "Luisa", **I want to** see user stats for water consumption on a given day and given week.

### PR DESCRIPTION
**Pull request by conconartist**
**Changes:**
- Added Hydration and CommunityHydration classes and corresponding tests to add functionality to the display for the FitLit application.  

**Issues:**
- Hydration and CommunityHydration classes are returning the information that is needed but there is an error in the display that needs to be looked at.  

- [ ] DRY and SRP
- [x] Tested Locally

**How to Review Changes or Manually Test Code:**
-Open Hydration.js and Hydration-test.js to view class and corresponding test to pass
-Open CommunityHydration.js and CommunityHydration-test.js to view class and corresponding test to pass
-Open scripts.js to view code and DOM manipulation
-Open index.html in browser to view displays 

**Notes:**
-I opened an issue for the display portion of Iteration 2.  Everything else should be working correctly.  I'd like to refactor the calculateTotalWeek method in CommunityHydration because it is pretty lengthy, but it works.

### CODE REVIEW

File: src/CommunityHydration.js [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+
+  calculateTotalWaterOnDay(userID, date) {
+    const userWater = this.hydrations.find(water => water.userID === userID && water.date === date);
+    return userWater.numOunces;
+  }
+
+  convertDateString(date) {
+    return parseInt(date.split('/').join(''));
+  }
+
```
Comment (srslie) [inline src/CommunityHydration.js:23]: This looks nice, I appreciate the clear names. We might want to talk to a mentor to help decide on ways to refactor or pull out smaller helper functions to make this a less scary big block of code.

File: src/scripts.js [hunk 2]
```diff
@@ -1,12 +1,16 @@
...
+const userMain = document.querySelector('.user-main')
+const userProfile = document.querySelector('.user-profile')
 const friends = document.querySelector('.friends')
-const userStepGoal = document.querySelector('.userStepGoal')
-const communityStepGoal = document.querySelector('.communityStepGoal')
-
+const userStepGoal = document.querySelector('.user-step-goal')
+const communityStepGoal = document.querySelector('.community-step-goal')
+const water = document.querySelector('.water');
+const waterStats = document.querySelector('.water-stats');
```
Comment (srslie) [inline src/scripts.js]: It looks like the class water-stats is not yet defined in our HTML, so referencing this is giving a 'null' error.

File: src/scripts.js [hunk 3]
```diff
@@ -36,13 +44,44 @@ const showProfile = () => {
...
 }
 
+//ADD TODAY's HYDRATION STATS:
+const showHydrationStats = () => {
+  waterStats.insertAdjacentHTML('beforeend',
+    `<p class="water-stats">Water consumed today: ${communityHydration.calculateTotalWaterOnDay(hydration.userID, "2019/09/20")} OZ</p>
+    `)
+}
+
+//ADD WEEKLY HYDRATION STATS:
```
Comment (srslie) [inline src/scripts.js:63]: Since the insertion is coming 'beforeend' and somehow we put friends div inside of graph, this isn't getting populated inside the div where we want it.

 We could also add parameters for that start and end date when calling the showHydrayionStatsWeek on pageLoad or whenever we call it, so we don't have to do it over and over in the calculateTotalWeek() call.

File: src/styles.css [hunk 4]
```diff
@@ -0,0 +1,71 @@
+body,html {
```
Comment (srslie) [inline src/styles.css:1]: You're a saint for doing CSS and I love this title font.

File: tests/CommunityHydration-test.js [hunk 5]
```diff
@@ -0,0 +1,50 @@
...
+const expect = chai.expect;
+
+const CommunityHydration = require('../src/CommunityHydration');
+const Hydration = require('../src/Hydration');
+
+describe('CommunityHydration', function() {
+  let communityHydration, hydration;
+
+  beforeEach(function() {
+    communityHydration = new CommunityHydration([
```
Comment (srslie) [inline tests/CommunityHydration-test.js:11]: Really thorough test cases, good call. I'm need to add more to mine.

File: tests/Hydration-test.js [hunk 6]
```diff
@@ -0,0 +1,32 @@
+const chai = require('chai');
+const expect = chai.expect;
+
```
Comment (srslie) [inline tests/Hydration-test.js:3]: I like how these classes are simple mirrors of each object in the data instance, I think that's what we're being guided toward.

File: src/index.html [hunk 7]
```diff
@@ -3,36 +3,69 @@
...
+          </p>
+          <p class="sleep-quality">
+          </p>
+        </div>
+      </article>
+    </section>
+    <section class="graph">
+      <h2>Graph</h2>
+    </graph>
+    <section class="friends">
```
Comment (srslie) [inline src/index.html:57]: Maybe the issue in display graph is because we made a closing </graph> instead of </section> so friends is showing up within that section div.

File: src/CommunityHydration.js [hunk 8]
```diff
@@ -0,0 +1,46 @@
...
+    const avgWaterConsumed = (waterConsumed.reduce((a, b) => a + b, 0)) / waterConsumed.length;
+    return avgWaterConsumed;
+  }
+
+  calculateTotalWaterOnDay(userID, date) {
+    const userWater = this.hydrations.find(water => water.userID === userID && water.date === date);
+    return userWater.numOunces;
+  }
+
+  convertDateString(date) {
```
Comment (srslie) [inline src/CommunityHydration.js:20]: Great pulling this out to a separate function. I know I use this in my data too, so I was thinking maybe 1) we just map the dates into this format on instantiation, or 2) we have it as a user method or something so we only have to write it once and pass in a user? I don't know the best way to dry this up so maybe we should ask a mentor.

File: src/scripts.js (hunk 2 above)
Comment (conconartist) [reply src/scripts.js]: @srslie Yes, thanks for catching that!!

File: src/scripts.js (hunk 3 above)
Comment (conconartist) [reply src/scripts.js:63]: @srslie That makes sense.  And we might need to adapt to whatever we ultimately end up using to display these graph results.

File: tests/Hydration-test.js (hunk 6 above)
Comment (conconartist) [reply tests/Hydration-test.js:3]: @srslie Agreed- I think that's the route to take for now!

File: tests/CommunityHydration-test.js (hunk 5 above)
Comment (conconartist) [reply tests/CommunityHydration-test.js:11]: @srslie Thank you!

File: src/index.html (hunk 7 above)
Comment (conconartist) [reply src/index.html:57]: @srslie Ahhh.... I'll play around with it to see if that's the case.

File: src/CommunityHydration.js (hunk 8 above)
Comment (conconartist) [reply src/CommunityHydration.js:20]: @srslie I was wondering about that, too.  I agree-- a good question to ask our mentors.

File: src/scripts.js [hunk 9]
```diff
@@ -4,8 +4,8 @@ const friends = document.querySelector('.friends')
 const userStepGoal = document.querySelector('.user-step-goal')
 const communityStepGoal = document.querySelector('.community-step-goal')
 const water = document.querySelector('.water');
-const waterStats = document.querySelector('.water-stats');
 const graph = document.querySelector('.graph');
+const graphTitle = document.querySelector('.title-graph');
```
Comment (conconartist) [inline src/scripts.js:8]: @srslie I added a querySelector for the Graph title to move the Hydration Weekly Stats underneath.  I'm wondering if we will want to change this when we implement the graph but set this up for now.

File: src/scripts.js (hunk 3 above)
Comment (conconartist) [reply src/scripts.js:63]: @srslie I think I've updated everything by now, so let me know if I'm missing anything! Otherwise, we should be good to merge.

File: src/scripts.js (hunk 9 above)
Comment (srslie) [reply src/scripts.js:8]: Looks good for now :) I assume a lot of our graph stuff may change with chart.js
